### ISSUE TITLE
Insecure method of sending mail

### ISSUE THREAD

**Issue by alanmburr** [OpenRoyalityFree/ContactForm#1]
Sending mail through JavaScript is great and all, but is a super insecure method. The SMTP Credentials are exposed publicly to anyone who visits the site, making it really easy for any hacker to fraudulently use the credentials.

Sending mail for a contact form should really be done on the backend, thus making it harder to expose these credentials,

**Comment by jaikt** [comment]
ah okay, i will fix this.

**Comment by MofhyDeveloper** [comment]
Okay, fix will come soon.
